Feature/refactory celery tasks
StartUpPlutusFi/plutusfi-mm-backend pull request #19
Opened 2022-11-16 20:15 UTC by th3maid

@suportebeloj 
Add new autotrade strategy to avoid awful bots
Remove useless functions from biconomy_core.py
Change logs file format to json
Change logs format in autotrade to make it better to read

2022-11-16 20:35 UTC, suportebeloj requested changes
please, remove empty json files

2022-11-16 20:35 UTC, suportebeloj commented on apps/autotrade/api/views.py
> +            elif set_status == "stop":
Existem 2 possíveis estados aqui, o elif não deveria ser utilizado nesse caso, uma vez que ou é "stop" ou "start"

2022-11-16 21:20 UTC, th3maid reviewed
Review bug, an  elif without else at autotrade ctrl view, fixed

2022-11-17 12:18 UTC, suportebeloj approved these changes

2022-11-17 12:20 UTC, merged